services:
  redis:
    image: redis:alpine
    container_name: portfolio_redis
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    ports:
      - "6381:6379"
    security_opt:
      - no-new-privileges
    # To prevent denial of service attacks
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    networks:
      - portfolio_db_net
    volumes:
      - redis_data:/data
  psql:
    image: postgres:latest
    container_name: portfolio_psql
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=ever
      - POSTGRES_DB=portfolio
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - portfolio_db_net
    user: postgres
volumes:
  psql_data:
  redis_data:

networks:
  portfolio_db_net:
