services:
  api:
    container_name: portfolio_wasm
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - portfolio_wasm_net
    env_file:
      - path: ./.env
        required: true
    ports:
      - "3002:3002"
    command: ["cargo", "run", "--release"]
  redis:
    image: redis:alpine
    container_name: portfolio_redis
    restart: always
    env_file:
      - path: ./.env
        required: true
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    ports:
      - "6381:6379"
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    networks:
      - portfolio_wasm_net
    volumes:
      - redis_data:/data
volumes:
  redis_data:

networks:
  portfolio_net:
