services:
  api:
    container_name: portfolio-rs-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - portfolio_wasm_net
    env_file:
      - path: ./.env
        required: true
    ports:
      - 3002:3002
    depends_on:
      - redis
    command: ["cargo", "run", "--release"]
  wasm:
    container_name: portfolio-rs-wasm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - portfolio_wasm_net
    env_file:
      - path: ./.env
        required: true
    ports:
      - "3003:3003"
    depends_on:
      - api
  redis:
    image: redis:alpine
    container_name: portfolio-rs-redis
    restart: always

    env_file:
      - path: ./.env
        required: true
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--port",
        "6389",
        "--appendonly",
        "yes",
      ]
    ports:
      - 6389:6389
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    networks:
      - portfolio_wasm_net
    volumes:
      - redis_data:/data
volumes:
  redis_data:
networks:
  portfolio_wasm_net:
