services:
  # wasm:
  #   container_name: portfolio-rs-wasm
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - portfolio_wasm_net
  #   environment:
  #     - RUST_LOG=portfolio=info,tower_http=info
  #     - LEPTOS_OUTPUT_NAME=portfolio
  #     - LEPTOS_SITE_ROOT=site
  #     - LEPTOS_SITE_PKG_DIR=pkg
  #     - LEPTOS_SITE_ADDR=0.0.0.0:3003
  #     - LEPTOS_RELOAD_PORT=3020
  #     - API_URL=portfolio-rs-api:3002
  #   env_file:
  #     - path: ./.env
  #       required: true
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     - api
  #     - redis
  api:
    container_name: portfolio-rs-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - portfolio_wasm_net
    env_file:
      - path: ./.env
        required: true
    environment:
      - PRODUCTION=false
      - API_VERSION=0.0.1
      - API_SERVER_URL=0.0.0.0:3002
      - RUST_LOG=api=debug,tower_http=info
      - EMAIL=ruizdiaz.oe@gmail.com
      - SMTP_USERNAME=ruizdiaz.oe@gmail.com
      - RUST_LOG=api=info,tower_http=info
    ports:
      - "3002:3002"
    depends_on:
      - redis
    command: ["cargo", "run", "--release"]
  redis:
    image: redis:alpine
    container_name: portfolio-rs-redis
    restart: always
    env_file:
      - path: ./.env
        required: true
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    networks:
      - portfolio_wasm_net
    volumes:
      - redis_data:/data
volumes:
  redis_data:
networks:
  portfolio_wasm_net:
