[serve]
address = "127.0.0.1"
port = 4001
open = false

[env]
CLIENT_PROCESS_NAME = "trunk"

[tasks.build]
command = "trunk"
args = ["build"]

[tasks.start-client]
command = "trunk"
args = ["serve", "${@}"]
